### ISSUE TITLE
Extract diseases treated

### ISSUE THREAD

**Issue by sandroacoelho** [sandroacoelho/drugs#4]
**Is your feature request related to a problem? Please describe.**

We have a bunch of leaflets in PDF. It would be nice to have this information  in sections, such as Diseases Treated, Side effects, components etc

**Describe the solution you'd like**

It would be nice to have classes by labs that knows what you want to extract

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ishi1702** [comment]
let me make a try
